sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 8
before_script:
  - npm install -g istanbul
  - npm run-script pretest
script:
  - ./node_modules/mocha/bin/_mocha --recursive
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- --recursive; exit 0
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js